name: build-push
on: workflow_dispatch
env:
  DOCKER_BUILDKIT: 1
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: ${{ github.repository }}/frontend
  BACKEND_IMAGE_NAME: ${{ github.repository }}/backend
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  build-backend:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Backend image
        uses: docker/build-push-action@v6
        id: push-backend
        with:
          context: .
          file: ./Dockerfile.prod
          target: backend
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest
    #  - name: Generate artifact attestation for Backend
    #    uses: actions/attest-build-provenance@v2
    #    with:
    #     subject-name: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}
    #     subject-digest: ${{ steps.push-backend.outputs.digest }}
    #     push-to-registry: true

  build-frontend:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Frontend image
        uses: docker/build-push-action@v6
        id: push-frontend
        with:
          context: .
          file: ./Dockerfile.prod
          target: frontend
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
      # - name: Generate artifact attestation for Frontend
      #   uses: actions/attest-build-provenance@v2
      #   with:
      #    subject-name: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}
      #    subject-digest: ${{ steps.push-frontend.outputs.digest }}
      #    push-to-registry: true
