# docker compose production configuration
---
services:
  frontend:
    image: ghcr.io/scstanton20/tago-analysis-runner/frontend:latest
    container_name: tago-runner-frontend
    networks:
      - traefik-public
      - backend
    #ports:
    #- 80:80
    restart: unless-stopped
    env_file: stack.env
    depends_on:
      backend:
        condition: service_healthy
    labels:
      traefik.enable: 'true'
      traefik.http.routers.tago-runner.rule: 'Host(`tago-runner.scstanton.net`)'
      traefik.http.routers.tago-runner.middlewares: 'secured@file,tago-auth'
      traefik.http.routers.tago-runner.entrypoints: 'https'
      traefik.http.middlewares.tago-auth.basicauth.users: 'parkwide:${BASIC_AUTH_PASS}'
      traefik.http.routers.tago-runner.tls: 'true'
      traefik.docker.network: 'traefik-public'

  backend:
    image: ghcr.io/scstanton20/tago-analysis-runner/backend:latest
    container_name: tago-runner-backend
    restart: unless-stopped
    volumes:
      - analysis-data:/app/analyses-storage
    networks:
      - backend
    env_file: stack.env
    ports:
      - 3000:3000
    environment:
      TZ: 'America/New_York'
      SECRET_KEY: ${SECRET_KEY}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'node -e "require(''http'').request(''http://localhost:3000/api/status'', { timeout: 2000 }, (res) => { const allowed = [200, 203]; process.exit(allowed.includes(res.statusCode) ? 0 : 1); }).on(''error'', () => process.exit(1)).end()"',
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

volumes:
  analysis-data:
    driver: local

networks:
  traefik-public:
    external: true
  backend:
    external: true
