# docker compose development configuration
---
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_WS_URL=ws://localhost:3000/ws
      - VITE_API_URL=http://localhost:3000
      - TZ='America/New_York'
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
      - analysis-data:/app/backend/analyses-storage
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  analysis-data:
    driver: local
