# ./docker-compose.dev.yml
---
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker-config/development/frontend.Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm --filter frontend dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  server:
    build:
      context: .
      dockerfile: ./docker-config/development/server.Dockerfile
    volumes:
      - .:/app
    command: pnpm --filter server dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development