# ./docker-compose.dev.yaml
---
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker-configs/development/frontend.Dockerfile
    volumes:
      - ./apps/frontend:/app/apps/frontend
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: .
      dockerfile: ./docker-configs/development/backend.Dockerfile
    volumes:
      - ./apps/backend/src:/app/apps/backend/src
      - analysis-data:/app/apps/backend/analyses-storage
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

volumes:
  analysis-data:
